---
title: Epidemiology of traumatic brain injury patients attending a tertiary care centre
  in eastern India
author: "Debojit Basak"
date: "05/06/2020"
output: word_document
---

# Abstract
Trauma is one of the leading causes of death in India. Road traffic accidents cause about 60% of all traumatic brain injuries (TBI) in India. [1] <!-- There shouldn't be any references in an abstract, please remove those -->According to an estimate 50% of trauma deaths in India is caused by Traumatic Brain Injury (TBI)<!-- You've already abbreviated TBI, no need to do it twice -->. [2]  The purpose of this study is to assess the prevalence, severity, cause, and outcome of admitted TBI patients.

## Method:
We will retrospectively analyse data from the Trauma Audit Filter Trial (TAFT). The data was collected from the tertiary care centre Seth Sukhlal Karnani Memorial Hospital (SSKM), Kolkata, West Bengal. The data collection period was October 2017 to January 2020. One project officer was appointed to collect data prospectively for eight hours per day in the emergency room. Vital signs i.e. blood pressure, heart rate, respiratory rate, spo2, Glasgow coma scale (GCS), and AVPU were measured in the emergency department. For measurement of blood pressure, heart rate, Spo2 calibrated electronic bp-machine and Spo2 machine was provided<!-- No need to be this detailed in the abstract -->. Data collector was trained to measure vitals at the start of the study. The project officer’s duty was divided into morning, evening and night shifts. Patient’s outcome was recorded from patients file till discharge or death. Data was uploaded in data server on weekly basis and data review was conducted. Audit of data collection and vital sign measurement was done quarterly. In addition to audit, project officer at quarterly interval was made to collect vitals of 10 patients with the Investigator on site to ensure that data quality and data integrity is maintained<!-- Same here, everything between the last comment and this one can be removed and kept for a full paper -->. We included all patients who were 18 years or older and presented to the emergency department (ED) and was admitted for TBI.

## Results:

```{r}
## Always start by loading the packages you use
library(rio)
library(tidyr)
library(dplyr)
library(stringr)

## Loading the csv file
data.dir <- getOption("data.dir")
if (is.null(data.dir))
    stop ("Please set the data directory using options(data.dir = \"<path to data>\").")
data_taft <- import(file.path(data.dir, "taft-dataset-2736-20200525172700.csv")) %>% as_tibble()

## Make sure injury and icd columns are character
data_taft <- data_taft %>% mutate(across(contains("inj"), ~as.character(.x)))

## Sorting file based on PID from smallest to largestx
PID_order <- order(data_taft$pid)
a <- data_taft[PID_order,]

## Apply filter to find all TBI patients in dataset using ICD 10 codes
icd.codes <- c("S065", "S063", "S020", "S008", "S021","S026", "S032", "S053",
               "S056", "S061", "S062", "S064", "S066", "S068", "S035")
pattern <- str_c(icd.codes, collapse = "|")
a <- unite(a, allinj, contains("icd"), sep = ",", remove = FALSE)
tbi <- filter(a, str_detect(allinj, pattern))

## To find no of male female and there percentage
males <- tbi$sex == 1
n.male <- sum(males)
p.male <- round(mean(males) * 100)

###replacing 999 with NA in column mortality

hd <- tbi[,62]
hd <- replace(hd,hd>3,NA)
hd <- as.factor(hd)

###to find % mortality


mortality1 <- tbi["mortalityfinal"] <- ifelse(hd == 0,"discharge",
                                              ifelse(hd == 1,"death",
                                                     ifelse(hd == 2, "alive and tranferred",
                                                            ifelse(hd == 3, "DAMA",0)
                                                            )
                                                     )
                                                )




b <- table(mortality1)
prop.table(b)
mortality_round <- round(prop.table(b),4)*100

##to find percentage transferred

transferred <- as.factor (tbi [,12])
transferred1 <- ifelse(transferred == 0,"direct","transferred")
trans_table <- table(transferred1)
prop.table(trans_table)
round(prop.table(trans_table),4)*100

##to find mode of transport

transport <- as.factor(tbi [,11])
transport1 <- ifelse(transport == 0, "ambulance","police")
transport_table <- table(transport1)
prop.table (transport_table)
round(prop.table(transport_table),2)*100

##to find mechanism of injury ## tried but failed 
##i tried to add ICD code for RTA, fall, assault and then tried to create a table but was unable
##i tried using replace , as well as ifelse but using ifelse would create a very long code. so i used a external calculator to add individual percent
injury <- as.factor (tbi [,9])
injury_table <- table(injury)
round(prop.table (injury_table),4)*100

##to find mean arterial pressure 

sbp_avg <- tbi["sbpfinal"] <- (tbi$sbp1+tbi$sbp2)/2
dbp_avg <- tbi["dbpfinal"] <- (tbi$dbp1+tbi$dbp2)/2

bp1 <- tbi["map1"] <- sbp_avg + dbp_avg
bp2 <- tbi["map2"] <- bp1 + dbp_avg
mean_arterial_pressure <- tbi["mapfinal"] <- bp2/3
##its almost a normal distribution curve
summary (mean_arterial_pressure) 

##creating a new column with colname GCS which will contain total gcs

G <- tbi["GCS"] <- tbi$egcs+tbi$vgcs+tbi$mgcs
gcs <- replace(G,G > 15 ,NA)

#breaking gcs into groups

gcs_groups <- cut(gcs, breaks = c(2,8,13,15), labels = c( "3-8","9-13","14-15"))
table

#creating table of GCS distribution
gcs_table <-table(gcs_groups)
round(prop.table(gcs_table),2)*100

###calculating proportion of patients in AVPU

avpu <- tbi[,33]
avpu <- replace(avpu,avpu>3,NA)

avpu1 <-  ifelse(avpu == 0,"Unresponsive",
                                              ifelse(avpu == 1,"Pain responsive",
                                                     ifelse(avpu == 2, "Voice responsive",
                                                            ifelse(avpu == 3, "Alert",0)
                                                     )
                                              )
)



avpu_table <- table(avpu1)

round(prop.table(avpu_table),2)*100

#breaking age into groups

age_groups <- cut(age, breaks = c(17,25,45,65,85), labels =  c("18-24","25-44","45-64","65+"))  

table (age_groups)

#to find number of ot done

#creating a seperate column surgery to contain to terms "conservative" , "intervention"
#inorder to do so first i replaced all zero's with 999 as it was errors while typing
s <- tbi[,61]
surg <- replace(s,s==0,999)
#then created a seperate column using ifelse 
surgery <- tbi["surgeryfinal"] <- ifelse(surg == 999,"conservative","intervention")
  
table_surgery <- table(surgery)
round(prop.table(table_surgery),2)*100

# Analysis

##crosstabulating map and mortality
map_table <- table(map_group, mortality1)

round(prop.table(map_table,1),2)*100


##crosstabulation between GCS and mortality

gcs_mortality <- table(gcs_groups, mortality1)

#calculating row% to calculate mortality in each gcs groups

round(prop.table(gcs_mortality,1),2)*100

##cross tabulation AVPU and mortality

avpu_mortality <- table (avpu1,mortality1)

#calculating row% to calculate mortality in each avpu groups

round(prop.table(avpu_mortality,1),2)*100

##crosstabulation between age and mortality


age_mortality <- table(age_groups,mortality1)


#calculating row% to calculate mortality in each age group

age_mortality_rounded <- round(prop.table(age_mortality,1),2)*100

##crosstabulation between gender and mortality

sex_mortality <- table (sex_1,mortality1)


#calculating row% to calculate mortality in each gender

sex_mortality_round <- round(prop.table(sex_mortality,1),2)*100





##crosstabulation between transfer status and mortality

trans_mortality <- table(tbi$tran, mortality1)

#calculating row% to calculate mortality in transfer status
round(prop.table(trans_mortality,1),2)*100


#comparing surgery with mortality 
surgery_mortality <- table(surgery,mortality1)
#calculating row% to calculate mortality among intervention and conservative managements
round(prop.table(surgery_mortality,1),2)*100
```

A total of `r nrow(tbi)` TBI patients were admitted during the period of our study. `r n.male` (`r p.male`%) were male. Median age of patients was 40 (IQR: 30 to 54; range: 18 to 85).There were 369(47.6%) Of all the TBI patients 655(84.4%) were transferred from other hospitals. Almost 741(95%) patients were brought to SSKM via ambulance. Mean arterial pressure among them were 84.5 (IQR: 81.17 to 88.88; range: 53.17 to 139.67).  340(44%) patients had GCS within range of 14-15 and 434 (56%) patients were Alert (A). Among 336 (43%) patients operative intervention was needed. Road traffic accident (RTA) accounts for majority of TBIs 430 (55.35%) followed by fall 177(22.81%). Of all the RTA’s, two wheeler accident consist of 335(43.19%). Mortality was 29.8% among these patients.  

## Conclusion
There has been a significant rise of trauma in India in last few decades of which TBI forms a major portion. Prevention, Pre-hospital care and rehabilitation are the needs of the hour as the burden of TBI is increasing. Major developing economy like India faces a major challenge in these fields. <!-- Altough true none of this relates to your aim. Remove and summarize your findings instead -->
