---
title: 'Epidemiolgy of falls among older adults : A single centre study from Mumbai'(As majority of old patients are from fall category (38/56).So my study title is like this)
author: "Jyoti Kamble"
date: "18/05/2020"
output:
  word_document: default
  html_document: default
---

# Introduction
Fall is an important cause and second leading cause  of injury morbidity and mortality in older adults world wide [1]<!-- There shouldn't be any references in an abstract, please remove those -->. The 2010 Global Burden of Disease and Injury Study estimated that 12% of all unintentional injury deaths are due to falls [2]. However, epidemiological information on fall is limited in low and middle income countries like India. High mortality due to fall injury amongst older ages is indicative of the need for a public health response to the issue<!-- This last sentence comes a bit "out of the blue", as it's not clearly connected to the previous sentence. I suggest you either move it to earlier in the paragraph or remove it-->.

# Aim
To investigate the pattern, characteristics and the context(This study is coding injuries as per ICD 10 so the reason for fall will be clear. This study uses time, activity(as per ICD 10) and the injury that will define context.)<!-- This sentence within parentheses is methods rather than aim, so I suggest you move it there--> of falls in Mumbai based on ICD -10 coding<!-- That you will do it based on ICD-coding is methods. Note that you are looking at this from a university hospital perspective, so to say that you are looking at falls in Mumbai, in general, is not true-->.

# Design
This is a single centre retrospective study<!-- Well, TAFT is prospective. Do you mean that your analysis is retrospective? In that case you can say that you conduct a retrospective analysis of a prospective cohort--> . The data collection for Trauma Audit Filter Trial (TAFT) was carried out from Dec 2017 - Mar 2018, Mumbai after obtaining approval from the Institute Ethics Committee<!-- I don't think you need to include the last part about IEC approval in an abstract -->.

# Methods
Data of 56 patients is taken from a trauma audit trial data set<!-- This is results, not methods-->. The inclusion criteria were all trauma patients visiting hospital in my working hours whose age is >/= 60 years and with history of fall<!-- You could also write: "We included all trauma..."-->. Data is collected by project officers in a rotating shifts. Informed consent is taken from all patients included in study. This study uses convenience sampling fall patients sample is taken from trauma population<!-- Not strictly. You are using a type of probability sampling as the start shift was random -->.(Convenience sampling is a type of non-probality sampling that involves the sample being drawn from that part of population that is close to hand.)<!-- Explanations like this are not needed in an abstract--> Data collection instrument is used for data entry and R analysis, ver 4.0 is used for data analysis. Variables like demographic profile (age, sex), vitals (Blood pressure, oyxgen saturation, pulse rate, respiratory rate, GCS within one hour of arrival to hospital), CT , X-ray, surgery will be used.Mechanism of injury and injuries related to patients are coded as per ICD - 10 and will be used. This study has used simple methods like logistic regression<!-- Why do you say that logistic regression is a simple method? No need for that.-->. For  assessment of the associations of the characteristics of respondents with falls, Odd Ratio (OR) with 95 % confidence interval were estimated.<!-- Write more direct: "Associations between patient characteristics and what? were assessed using logistic regression", or even better" We assessed associations between ..."-->

# Results
Out of which 456 trauma patients, 64 were above 60 years and 396 were below 60 years. The  status was pending for 8 patients so they are excluded and hence the study sample is for 56 patients. My dataset in R studio shows 56 observations and 132 variables.  Out of 56 patients, 38 comes under fall, 12 were transport accidents and 6 comes under Event of undetermined intent. Summarize your results. Give the number of observations in the study sample. Give summary statistics. Include a table that describes your sample, commonly referred to as Table 1. (This section will have a missing numbers as you have not yet started analyzing the data)<!-- Please include the code that you've used to generate these numbers here in the abstract file -->

# Conclusion
Give a short answer to your aim.



