---
title: "Adult age and Red triage"
author: "TAMAL"
date: "06/06/2020"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Triage is very necessary for trauma patients because proper triaging indicate level of care required for the patients.Triage category red is for very serious patients where green triage is for minor injury.
Red triage mostly used for adult age rather than senior adult according to injury data.

## Aim
To Find profile for red triage & involvement of adult age.

## Study design
1. Selection of adult age group i.e 18 -59 years of age.
2. Finding the injury report & triaging information from medical report.
3.collect medical History of the injured patient.
4.Collect treatment records of injured patient(i.e 1st treatment time & condidition of patient, transfer history, diagnostic for finding injury.)

## Methods
1. Choosing of sample i.e patients age group of 18-59 years.
2. Sort out patients asper triage cateory.
3. Collection of medical history & findings.
4. Analyse data for find out result i.e red triage percentage for the previouly mentioned age group & also finding out some other factors like initial triage category treatment for the patient with triage red.

## Result
Total number of collected trauma patients are 5600, triage red category patients are 273 under this category adult age patients are 104 so 38% of triage red category.

## Conclusion
So, we can conclude that only 38% of the collected patients are under triage category red due to RTA.


